//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kryptor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kryptor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111	abacus
        ///11112	abdomen
        ///11113	abdominal
        ///11114	abide
        ///11115	abiding
        ///11116	ability
        ///11121	ablaze
        ///11122	able
        ///11123	abnormal
        ///11124	abrasion
        ///11125	abrasive
        ///11126	abreast
        ///11131	abridge
        ///11132	abroad
        ///11133	abruptly
        ///11134	absence
        ///11135	absentee
        ///11136	absently
        ///11141	absinthe
        ///11142	absolute
        ///11143	absolve
        ///11144	abstain
        ///11145	abstract
        ///11146	absurd
        ///11151	accent
        ///11152	acclaim
        ///11153	acclimate
        ///11154	accompany
        ///11155	account
        ///11156	accuracy
        ///11161	accurate
        ///11162	accustom
        ///11163	acetone
        ///11164	achiness
        ///11165	aching
        ///11166	acid
        ///112 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist {
            get {
                return ResourceManager.GetString("wordlist", resourceCulture);
            }
        }
    }
}
